name: Build BTLoader (arm64)

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: "(Optional) BTLoader commit ID to build at"
        default: ""
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build BTLoader (rootless)
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout CloudySn0w/BTLoader
        uses: actions/checkout@v4
        with:
          repository: CloudySn0w/BTLoader
          ref: ${{ github.event.inputs.commit_id || 'main' }}
          path: main
          submodules: true

      - name: Install Dependencies
        run: brew install make dpkg ldid

      - name: Add GNU Make to PATH
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> "$GITHUB_PATH"

      - name: Download roothide Theos
        uses: actions/checkout@v4
        with:
          repository: roothide/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Get BTLoader Version
        run: |
          BTLOADER_VERSION=$(awk '/Version:/ {print $2}' main/control)
          echo "BTLOADER_VERSION=${BTLOADER_VERSION}" >> "$GITHUB_ENV"
          echo "$BTLOADER_VERSION"

      - name: Build Package
        run: |
          cd ${{ github.workspace }}/main
          export THEOS_PACKAGE_SCHEME=roothide
          make package FINALPACKAGE=1
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Get package filename
        id: package_name
        run: |
          echo "package=$(ls -t main/packages/*.deb | head -n1)" >> "$GITHUB_OUTPUT"

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: BTLoader-rootless_${{ env.BTLOADER_VERSION }}
          path: ${{ steps.package_name.outputs.package }}
          if-no-files-found: error

      - name: Upload deb for commit job
        uses: actions/upload-artifact@v4
        with:
          name: deb-btloader
          path: ${{ steps.package_name.outputs.package }}

  commit-debs:
    name: Commit .debs to repo
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download deb
        uses: actions/download-artifact@v4
        with:
          name: deb-btloader
          path: debs/

      - name: Commit new .debs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add debs/*.deb
          git commit -m "chore: add BTLoader rootless + rootfull debs [ci skip]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
